const STATE = {
  IDLE: 0,
  PACKET_TYPE_READING: 1,
  SUBJECT_READING: 2,
  EVENT_DATA_READING: 3,
  REQUEST_DATA_READING: 4,
  SUCCESS_RESPONSE_DATA_READING: 5,
  FAILURE_RESPONSE_DATA_READING: 6
};

const LENGTH = {
  PACKET_TYPE: 2,
  SUBJECT: 4,
  SET_RELAY: {
    ERROR: 1
  },
  GET_RELAY: {
    ERROR: 1
  },
  TOGGLE_RELAY: {
    ERROR: 1
  },
  GET_SOIL_MOISTURE: {
    ERROR: 1
  },
  GET_DHT: {
    ERROR: 1
  },
  GET_DS18B20: {
    ERROR: 1
  },
  SOIL_MOISTURE: {
    SENSOR_ID: 4,
    MOISTURE: 7
  },
  DHT: {
    SENSOR_ID: 3,
    HUMIDITY: 7,
    TEMPERATURE: 8
  },
  DS18B20: {
    SENSOR_ID: 3,
    TEMPERATURE: 9
  }
};

const ERROR = {
  SET_RELAY: {
    INVALID_RELAY_ID: 0
  },
  GET_RELAY: {
    INVALID_RELAY_ID: 0
  },
  TOGGLE_RELAY: {
    INVALID_RELAY_ID: 0
  },
  GET_SOIL_MOISTURE: {
    INVALID_SENSOR_ID: 0
  },
  GET_DHT: {
    INVALID_SENSOR_ID: 0
  },
  GET_DS18B20: {
    INVALID_SENSOR_ID: 0
  }
};

const PACKET_TYPE = {
  EVENT: 0b00,
  REQUEST: 0b01,
  SUCCESS_RESPONSE: 0b10,
  FAILURE_RESPONSE: 0b11
};

const INBOUND_EVENT = {
  SOIL_MOISTURE: 0b0000,
  DHT: 0b0001,
  DS18B20: 0b0010
};

const INBOUND_EVENT_NAME = {
  SOIL_MOISTURE: 'soil-moisture',
  DHT: 'dht',
  DS18B20: 'ds18b20'
};

const OUTBOUND_EVENT = {
};

const OUTBOUND_REQUEST = {
  SET_RELAY: 0b0000,
  GET_RELAY: 0b0001,
  TOGGLE_RELAY: 0b0010,
  GET_SOIL_MOISTURE: 0b0011,
  GET_DHT: 0b0100,
  GET_DS18B20: 0b0101
};

module.exports = {
  STATE,
  LENGTH,
  ERROR,
  PACKET_TYPE,
  INBOUND_EVENT,
  INBOUND_EVENT_NAME,
  OUTBOUND_EVENT,
  OUTBOUND_REQUEST
};
